name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
      
permissions:
  contents: write # ESSENTIEEL: Geeft de actie toestemming om te schrijven naar een branch

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Gebruik de nieuwste versie
      - uses: actions/setup-python@v5 # Gebruik de nieuwste versie
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin # Installeer dependencies in één keer
      - run: mkdocs gh-deploy --force
